services:

    sauvabelin.list.rule_mailing_lists:
        class: SauvabelinBundle\ListModel\RuleMailingListsList
        tags:
            - { name: netbs.list.model }

    sauvabelin.list.redirect_mailing_lists:
        class: SauvabelinBundle\ListModel\RedirectMailingListsList
        tags:
            - { name: netbs.list.model }

    sauvabelin.list.displayable_mailing_lists:
        class: SauvabelinBundle\ListModel\DisplayableMailingListsList
        tags:
            - { name: netbs.list.model }

    sauvabelin.list.latest_accounts:
        class: SauvabelinBundle\ListModel\LatestAccountsCreatedList
        tags:
            - { name: netbs.list.model }

    sauvabelin.automatic.gars_vieux:
        class: SauvabelinBundle\Automatics\GarsQuiBougentAutomatic
        tags:
          - { name: netbs.list.model }
          - { name: netbs.automatic_list }


    sauvabelin.automatic.test_entree:
        class: SauvabelinBundle\Automatics\TestDentreeAutomatic
        tags:
          - { name: netbs.list.model }
          - { name: netbs.automatic_list }