services:

#actions
    netbs.core.list.action.link:
        class: NetBS\CoreBundle\ListModel\Action\LinkAction
        arguments:
            - "@router"
        tags:
            - {name: netbs.list_action }

    netbs.core.list.action.icon:
        class: NetBS\CoreBundle\ListModel\Action\IconAction
        arguments:
            - "@router"
        tags:
            - {name: netbs.list_action }

    netbs.core.list.action.remove:
        class: NetBS\CoreBundle\ListModel\Action\RemoveAction
        arguments:
            - "@security.authorization_checker"
            - "@router"
        tags:
            - {name: netbs.list_action }

    netbs.core.list.action.modal:
        class: NetBS\CoreBundle\ListModel\Action\ModalAction
        arguments:
            - "@twig.extension.assets"
            - "@netbs.core.twig.assets_extension"
            - "@router"
        tags:
            - {name: netbs.list_action }

#listes

    netbs.core.list.news:
        class: NetBS\CoreBundle\ListModel\NewsList
        tags:
            - { name: netbs.list.model }

    netbs.core.list.news_channels:
        class: NetBS\CoreBundle\ListModel\NewsChannelsList
        tags:
            - { name: netbs.list.model }

    netbs.core.list.parameters:
        class: NetBS\CoreBundle\ListModel\ParametersList
        tags:
            - { name: netbs.list.model }

    netbs.core.list.basic_renderer:
        class: NetBS\CoreBundle\ListModel\BasicRenderer
        arguments:
            - "@twig"
        tags:
            - { name: netbs.list.renderer }

    netbs.core.list.netbs_renderer:
        class: NetBS\CoreBundle\ListModel\NetBSRenderer
        arguments:
            - "@twig"
            - "@event_dispatcher"
        tags:
            - { name: netbs.list.renderer }

    netbs.core.list.huge_renderer:
        class: NetBS\CoreBundle\ListModel\HugeListRenderer
        arguments:
            - "@twig"
        tags:
            - { name: netbs.list.renderer }

    netbs.core.list.action_column:
        class: NetBS\CoreBundle\ListModel\Column\ActionColumn
        arguments:
            - "@netbs.core.list_actions_manager"
        tags:
            - { name: netbs.list.column }

    netbs.core.list.link_column:
        class: NetBS\CoreBundle\ListModel\Column\LinkColumn
        arguments:
            - "@router.default"
        tags:
            - { name: netbs.list.column }

    netbs.core.list.remove_from_dynamic_column:
        class: NetBS\CoreBundle\ListModel\Column\RemoveFromDynamicColumn
        arguments:
            - "@router.default"
        tags:
            - { name: netbs.list.column }

    netbs.core.list.popover_column:
        class: NetBS\CoreBundle\ListModel\Column\PopoverColumn
        tags:
            - { name: netbs.list.column }

    netbs.core.list.array_column:
        class: NetBS\CoreBundle\ListModel\Column\ArrayColumn
        tags:
            - { name: netbs.list.column }

    netbs.core.list.helper_column:
        class: NetBS\CoreBundle\ListModel\Column\HelperColumn
        arguments:
            - "@netbs.core.twig.helper_extension"
            - "@netbs.core.helper_manager"
        tags:
            - { name: netbs.list.column }

    netbs.core.list.xeditable_column:
        class: NetBS\CoreBundle\ListModel\Column\XEditableColumn
        arguments:
            - "@netbs.core.twig.xeditable_extension"
        tags:
            - { name: netbs.list.column }

    netbs.core.list.logged_changes:
        class: NetBS\CoreBundle\ListModel\LoggedChangesList
        tags:
            - { name: netbs.list.model }